CREATE TABLE user_table (

CPF VARCHAR (11) PRIMARY KEY,
SENHA VARCHAR (150),
ATIVO BOOLEAN DEFAULT TRUE,
CEP VARCHAR(9),
LOGRADOURO VARCHAR(150),
BAIRRO VARCHAR(250),
COMPLEMENTO VARCHAR(250),
UF VARCHAR(50)
);