CREATE TABLE INFORMACOES_CIDADAO (

    RU INT NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(11),
    OCORRIDO VARCHAR(30),
    AGENTE VARCHAR(100),
    DATAA DATE,
    VALOR DOUBLE,
    CEP VARCHAR(9),
    LOGRADOURO VARCHAR(150),
    COMPLEMENTO VARCHAR(250),
    BAIRRO VARCHAR(250),
    UF VARCHAR(50),
    SITUACAO VARCHAR(10),
    ATIVO BOOLEAN DEFAULT TRUE,

    PRIMARY KEY (RU,CPF),

    FOREIGN KEY (CPF)
    REFERENCES user_table (CPF)

    );